#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       a Z shell variant and "noglob" is set in .zshrc, bash $0 "$@" will fail.
#       But bash will be invoked anyway.
#
#   (2) The Java Virtual Machine's default charset must be UTF-8 and the user
#       country must be US. (Or the Java locale must be set.)

##############################################################################

set -o nounset

APP_NAME="Gradle"
APP_HOME=$( cd "${APP_HOME_FOLDER:-.}" && pwd -P ) || exit

APP_JAR="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"
APP_PROPERTIES="${APP_HOME}/gradle/wrapper/gradle-wrapper.properties"

exec "$JAVACMD" \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  -Dorg.gradle.java.home="$JAVA_HOME" \
  -cp "$APP_JAR" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
